version: '3'
services:
  bitcoind:
    restart: always
    image: chaintope/bitcoin
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./bitcoin:/root/.bitcoin
    networks:
      default: {}
      vpcbr:
        ipv4_address: 10.5.0.10
    command: bitcoind -printtoconsole
  bitcore:
    restart: always
    image: chaintope/bitcore
    ports:
      - "3001:3001"
    volumes:
      - "./bitcore/bitcore-node.json:/root/.bitcore/bitcore-node.json"
      - "./bitcore/bitcoin.conf:/root/.bitcore/data/bitcoin.conf"
    depends_on:
      - bitcoind
    networks:
      default: {}
      vpcbr:
        ipv4_address: 10.5.0.11     
networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
